# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\frmconfigbox.ui'
#
# Created: Sat Oct 22 15:55:21 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_configBox(object):
    def setupUi(self, configBox):
        configBox.setObjectName(_fromUtf8("configBox"))
        configBox.resize(743, 625)
        self.verticalLayout = QtGui.QVBoxLayout(configBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_title = QtGui.QWidget(configBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_title.sizePolicy().hasHeightForWidth())
        self.widget_title.setSizePolicy(sizePolicy)
        self.widget_title.setMinimumSize(QtCore.QSize(100, 28))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_title)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget_menu = QtGui.QWidget(self.widget_title)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_menu.sizePolicy().hasHeightForWidth())
        self.widget_menu.setSizePolicy(sizePolicy)
        self.widget_menu.setObjectName(_fromUtf8("widget_menu"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_menu)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))
        self.horizontalLayout.addWidget(self.btnMenu_Close)
        self.horizontalLayout_2.addWidget(self.widget_menu)
        self.verticalLayout.addWidget(self.widget_title)
        self.widget_main = QtGui.QWidget(configBox)
        self.widget_main.setStyleSheet(_fromUtf8("font: 11pt \"微软雅黑\";"))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_main)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.widget_main)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 20, 631, 411))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(150, 40, 141, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(20, 270, 81, 31))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(140, 280, 89, 16))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(220, 280, 89, 16))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(150, 100, 141, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(150, 160, 141, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(60, 100, 71, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(70, 160, 61, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 470, 621, 34))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnOk_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.btnOk_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOk_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOk_2.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk_2.setIcon(icon)
        self.btnOk_2.setIconSize(QtCore.QSize(20, 20))
        self.btnOk_2.setObjectName(_fromUtf8("btnOk_2"))
        self.horizontalLayout_4.addWidget(self.btnOk_2)
        self.btnCancel_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.btnCancel_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel_2.setStyleSheet(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel_2.setIcon(icon1)
        self.btnCancel_2.setIconSize(QtCore.QSize(20, 20))
        self.btnCancel_2.setObjectName(_fromUtf8("btnCancel_2"))
        self.horizontalLayout_4.addWidget(self.btnCancel_2)
        self.labIcoMain_3 = QtGui.QLabel(self.tab_2)
        self.labIcoMain_3.setGeometry(QtCore.QRect(10, 30, 45, 45))
        self.labIcoMain_3.setStyleSheet(_fromUtf8("border-image: url(:/image/myconfig.png);"))
        self.labIcoMain_3.setText(_fromUtf8(""))
        self.labIcoMain_3.setObjectName(_fromUtf8("labIcoMain_3"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(80, 20, 645, 487))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 450, 621, 34))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnOk = QtGui.QPushButton(self.layoutWidget)
        self.btnOk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOk.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOk.setStyleSheet(_fromUtf8(""))
        self.btnOk.setIcon(icon)
        self.btnOk.setIconSize(QtCore.QSize(20, 20))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_3.addWidget(self.btnOk)
        self.btnCancel = QtGui.QPushButton(self.layoutWidget)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel.setStyleSheet(_fromUtf8(""))
        self.btnCancel.setIcon(icon1)
        self.btnCancel.setIconSize(QtCore.QSize(20, 20))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 657, 421))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup_2 = QtGui.QButtonGroup(configBox)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.gridLayout.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.gridLayout.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup_2.addButton(self.radioButton)
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.buttonGroup = QtGui.QButtonGroup(configBox)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout.addWidget(self.radioButton_5, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 541, 341))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 11, 2, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_4.addWidget(self.lineEdit_18, 1, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_4.addWidget(self.lineEdit_11, 9, 1, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_4.addWidget(self.lineEdit_14, 9, 3, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_4.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 3, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_4.addWidget(self.lineEdit_15, 11, 1, 1, 1)
        self.lineEdit_51 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_51.setObjectName(_fromUtf8("lineEdit_51"))
        self.gridLayout_4.addWidget(self.lineEdit_51, 3, 3, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_4.addWidget(self.lineEdit_12, 4, 1, 1, 3)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 9, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 11, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 9, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_4.addWidget(self.lineEdit_21, 2, 2, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_4.addWidget(self.lineEdit_22, 2, 3, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_4.addWidget(self.lineEdit_20, 1, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 11, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 0, 1, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_4.addWidget(self.lineEdit_13, 6, 1, 1, 3)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_49 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_49.setObjectName(_fromUtf8("lineEdit_49"))
        self.gridLayout_4.addWidget(self.lineEdit_49, 3, 1, 1, 1)
        self.lineEdit_50 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_50.setObjectName(_fromUtf8("lineEdit_50"))
        self.gridLayout_4.addWidget(self.lineEdit_50, 3, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_4.addWidget(self.label_33, 7, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 8, 0, 1, 1)
        self.lineEdit_55 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_55.setObjectName(_fromUtf8("lineEdit_55"))
        self.gridLayout_4.addWidget(self.lineEdit_55, 7, 1, 1, 3)
        self.lineEdit_56 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_56.setObjectName(_fromUtf8("lineEdit_56"))
        self.gridLayout_4.addWidget(self.lineEdit_56, 8, 1, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 12, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 541, 361))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_57 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_57.setObjectName(_fromUtf8("lineEdit_57"))
        self.gridLayout_3.addWidget(self.lineEdit_57, 6, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 8, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 2, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_3.addWidget(self.lineEdit_17, 1, 2, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_3.addWidget(self.lineEdit_7, 4, 1, 1, 3)
        self.lineEdit_6 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_3.addWidget(self.lineEdit_6, 8, 1, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_3.addWidget(self.lineEdit_9, 8, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 3, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 11, 2, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_3.addWidget(self.lineEdit_19, 1, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_3.addWidget(self.lineEdit_10, 11, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_3.addWidget(self.lineEdit_16, 2, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_3.addWidget(self.lineEdit_2, 11, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_3.addWidget(self.lineEdit_8, 5, 1, 1, 3)
        self.lineEdit_23 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_3.addWidget(self.lineEdit_23, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_3.addWidget(self.lineEdit_24, 2, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 12, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 11, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 3, 0, 1, 1)
        self.lineEdit_52 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_52.setObjectName(_fromUtf8("lineEdit_52"))
        self.gridLayout_3.addWidget(self.lineEdit_52, 3, 1, 1, 1)
        self.lineEdit_53 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_53.setObjectName(_fromUtf8("lineEdit_53"))
        self.gridLayout_3.addWidget(self.lineEdit_53, 3, 2, 1, 1)
        self.lineEdit_54 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_54.setObjectName(_fromUtf8("lineEdit_54"))
        self.gridLayout_3.addWidget(self.lineEdit_54, 3, 3, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 6, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 7, 0, 1, 1)
        self.lineEdit_58 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_58.setObjectName(_fromUtf8("lineEdit_58"))
        self.gridLayout_3.addWidget(self.lineEdit_58, 7, 1, 1, 3)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 3)
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.labIcoMain_2 = QtGui.QLabel(self.tab)
        self.labIcoMain_2.setGeometry(QtCore.QRect(10, 30, 45, 45))
        self.labIcoMain_2.setStyleSheet(_fromUtf8("border-image: url(:/image/myconfig.png);"))
        self.labIcoMain_2.setText(_fromUtf8(""))
        self.labIcoMain_2.setObjectName(_fromUtf8("labIcoMain_2"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.verticalLayout.addWidget(self.widget_main)

        self.retranslateUi(configBox)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(configBox)

    def retranslateUi(self, configBox):
        configBox.setWindowTitle(_translate("configBox", "提示", None))
        self.btnMenu_Close.setToolTip(_translate("configBox", "关闭", None))
        self.label_23.setText(_translate("configBox", "默认连接地址：", None))
        self.label_24.setText(_translate("configBox", "测试项目", None))
        self.radioButton_6.setText(_translate("configBox", "MAC", None))
        self.radioButton_7.setText(_translate("configBox", "SN", None))
        self.label_25.setText(_translate("configBox", "用户名：", None))
        self.label_26.setText(_translate("configBox", "密码：", None))
        self.btnOk_2.setText(_translate("configBox", "确定(&O)", None))
        self.btnCancel_2.setText(_translate("configBox", "取消(&C)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("configBox", "测试工作配置", None))
        self.btnOk.setText(_translate("configBox", "确定(&O)", None))
        self.btnCancel.setText(_translate("configBox", "取消(&C)", None))
        self.radioButton_3.setText(_translate("configBox", "测试2.4G和5G", None))
        self.radioButton_2.setText(_translate("configBox", "仅测试5G", None))
        self.radioButton.setText(_translate("configBox", "仅测试2.4G", None))
        self.radioButton_5.setText(_translate("configBox", "测试不通过也写art区", None))
        self.label_22.setText(_translate("configBox", "chain", None))
        self.label.setText(_translate("configBox", "ht40 power limit", None))
        self.label_4.setText(_translate("configBox", "tx ht40", None))
        self.label_31.setText(_translate("configBox", "rx", None))
        self.label_13.setText(_translate("configBox", "ppm limit", None))
        self.label_20.setText(_translate("configBox", "速率", None))
        self.label_14.setText(_translate("configBox", "pcdac", None))
        self.label_15.setText(_translate("configBox", "ht20 power limit", None))
        self.label_19.setText(_translate("configBox", "频率", None))
        self.label_12.setText(_translate("configBox", "线损(频率-线损)", None))
        self.label_3.setText(_translate("configBox", "tx ht20", None))
        self.label_11.setText(_translate("configBox", "频率(频率-线损)", None))
        self.label_33.setText(_translate("configBox", "速率(速率-功率)", None))
        self.label_34.setText(_translate("configBox", "功率(速率-功率)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("configBox", "2.4G", None))
        self.label_8.setText(_translate("configBox", "ppm limit", None))
        self.label_17.setText(_translate("configBox", "速率", None))
        self.label_21.setText(_translate("configBox", "chain", None))
        self.label_2.setText(_translate("configBox", "ht40 power limit", None))
        self.label_18.setText(_translate("configBox", "频率", None))
        self.label_5.setText(_translate("configBox", "tx ht20", None))
        self.label_7.setText(_translate("configBox", "线损(频率-线损)", None))
        self.label_9.setText(_translate("configBox", "pcdac", None))
        self.label_10.setText(_translate("configBox", "ht20 power limit", None))
        self.label_16.setText(_translate("configBox", "tx ht40", None))
        self.label_6.setText(_translate("configBox", "频率(频率-线损)", None))
        self.label_32.setText(_translate("configBox", "rx", None))
        self.label_35.setText(_translate("configBox", "速率(速率-功率)", None))
        self.label_36.setText(_translate("configBox", "功率(速率-功率)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("configBox", "5G", None))
        self.radioButton_4.setText(_translate("configBox", "测试通过才写art区", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("configBox", "测试项目配置", None))

