# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\ui\frmconfigbox.ui'
#
# Created: Tue Feb 14 16:49:03 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_configBox(object):
    def setupUi(self, configBox):
        configBox.setObjectName(_fromUtf8("configBox"))
        configBox.resize(787, 711)
        self.verticalLayout = QtGui.QVBoxLayout(configBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_title = QtGui.QWidget(configBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_title.sizePolicy().hasHeightForWidth())
        self.widget_title.setSizePolicy(sizePolicy)
        self.widget_title.setMinimumSize(QtCore.QSize(100, 28))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_title)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget_menu = QtGui.QWidget(self.widget_title)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_menu.sizePolicy().hasHeightForWidth())
        self.widget_menu.setSizePolicy(sizePolicy)
        self.widget_menu.setObjectName(_fromUtf8("widget_menu"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_menu)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))
        self.horizontalLayout.addWidget(self.btnMenu_Close)
        self.horizontalLayout_2.addWidget(self.widget_menu)
        self.verticalLayout.addWidget(self.widget_title)
        self.widget_main = QtGui.QWidget(configBox)
        self.widget_main.setStyleSheet(_fromUtf8("font: 11pt \"微软雅黑\";"))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_main)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabWidget_2 = QtGui.QTabWidget(self.widget_main)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(70, 20, 691, 521))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 651, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.toolBox_3 = QtGui.QToolBox(self.tab_5)
        self.toolBox_3.setGeometry(QtCore.QRect(10, 10, 351, 301))
        self.toolBox_3.setStyleSheet(_fromUtf8(""))
        self.toolBox_3.setObjectName(_fromUtf8("toolBox_3"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 351, 214))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.tableWidget_6 = QtGui.QTableWidget(self.page_6)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget_6.setLineWidth(1)
        self.tableWidget_6.setRowCount(20)
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.toolBox_3.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.tableWidget_7 = QtGui.QTableWidget(self.page_7)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_7.setLineWidth(0)
        self.tableWidget_7.setRowCount(20)
        self.tableWidget_7.setObjectName(_fromUtf8("tableWidget_7"))
        self.tableWidget_7.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        self.toolBox_3.addItem(self.page_7, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.tableWidget_8 = QtGui.QTableWidget(self.page_8)
        self.tableWidget_8.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget_8.setRowCount(20)
        self.tableWidget_8.setObjectName(_fromUtf8("tableWidget_8"))
        self.tableWidget_8.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        self.toolBox_3.addItem(self.page_8, _fromUtf8(""))
        self.toolBox_4 = QtGui.QToolBox(self.tab_5)
        self.toolBox_4.setGeometry(QtCore.QRect(380, 10, 251, 301))
        self.toolBox_4.setObjectName(_fromUtf8("toolBox_4"))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 251, 243))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.tableWidget_9 = QtGui.QTableWidget(self.page_9)
        self.tableWidget_9.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.tableWidget_9.setLineWidth(0)
        self.tableWidget_9.setRowCount(20)
        self.tableWidget_9.setObjectName(_fromUtf8("tableWidget_9"))
        self.tableWidget_9.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        self.toolBox_4.addItem(self.page_9, _fromUtf8(""))
        self.page_10 = QtGui.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.tableWidget_10 = QtGui.QTableWidget(self.page_10)
        self.tableWidget_10.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.tableWidget_10.setRowCount(35)
        self.tableWidget_10.setObjectName(_fromUtf8("tableWidget_10"))
        self.tableWidget_10.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        self.toolBox_4.addItem(self.page_10, _fromUtf8(""))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 330, 581, 111))
        self.groupBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(290, 30, 131, 21))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(430, 30, 131, 21))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(290, 70, 131, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_14.setGeometry(QtCore.QRect(430, 70, 131, 21))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(0, 30, 128, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 30, 131, 21))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(0, 70, 128, 21))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_28.setGeometry(QtCore.QRect(140, 70, 131, 21))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.toolBox = QtGui.QToolBox(self.tab_6)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 351, 301))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 351, 214))
        self.page.setObjectName(_fromUtf8("page"))
        self.tableWidget = QtGui.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.tableWidget_4 = QtGui.QTableWidget(self.page_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget_4.setRowCount(20)
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.tableWidget_5 = QtGui.QTableWidget(self.page_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.tableWidget_5.setRowCount(20)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.toolBox_2 = QtGui.QToolBox(self.tab_6)
        self.toolBox_2.setGeometry(QtCore.QRect(380, 10, 251, 301))
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.tableWidget_2 = QtGui.QTableWidget(self.page_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.tableWidget_2.setRowCount(20)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.toolBox_2.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 251, 243))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.tableWidget_3 = QtGui.QTableWidget(self.page_5)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 251, 241))
        self.tableWidget_3.setRowCount(35)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.toolBox_2.addItem(self.page_5, _fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 330, 581, 111))
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 131, 21))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(430, 30, 131, 21))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(290, 70, 131, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 70, 131, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(0, 30, 128, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 30, 131, 21))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(0, 70, 128, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 70, 131, 21))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.labIcoMain_2 = QtGui.QLabel(self.tab)
        self.labIcoMain_2.setGeometry(QtCore.QRect(10, 30, 45, 45))
        self.labIcoMain_2.setStyleSheet(_fromUtf8("border-image: url(:/image/myconfig.png);"))
        self.labIcoMain_2.setText(_fromUtf8(""))
        self.labIcoMain_2.setObjectName(_fromUtf8("labIcoMain_2"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 590, 621, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnOk = QtGui.QPushButton(self.layoutWidget)
        self.btnOk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOk.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOk.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon)
        self.btnOk.setIconSize(QtCore.QSize(20, 20))
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_3.addWidget(self.btnOk)
        self.btnCancel = QtGui.QPushButton(self.layoutWidget)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel.setStyleSheet(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon1)
        self.btnCancel.setIconSize(QtCore.QSize(20, 20))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 20, 631, 511))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(150, 40, 141, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(150, 100, 141, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(150, 160, 141, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(60, 100, 71, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(70, 160, 61, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(380, 100, 54, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(380, 160, 54, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(460, 100, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(460, 160, 113, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 230, 601, 71))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_6.setGeometry(QtCore.QRect(40, 30, 89, 16))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_7.setGeometry(QtCore.QRect(150, 30, 89, 16))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 320, 601, 71))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_8.setGeometry(QtCore.QRect(40, 30, 89, 16))
        self.radioButton_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_8)
        self.radioButton_9.setGeometry(QtCore.QRect(150, 30, 89, 16))
        self.radioButton_9.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 410, 601, 81))
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 40, 214, 19))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup_2 = QtGui.QButtonGroup(configBox)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 40, 215, 19))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(280, 40, 214, 19))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 590, 621, 34))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnOk_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.btnOk_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOk_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOk_2.setStyleSheet(_fromUtf8(""))
        self.btnOk_2.setIcon(icon)
        self.btnOk_2.setIconSize(QtCore.QSize(20, 20))
        self.btnOk_2.setObjectName(_fromUtf8("btnOk_2"))
        self.horizontalLayout_4.addWidget(self.btnOk_2)
        self.btnCancel_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.btnCancel_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel_2.setStyleSheet(_fromUtf8(""))
        self.btnCancel_2.setIcon(icon1)
        self.btnCancel_2.setIconSize(QtCore.QSize(20, 20))
        self.btnCancel_2.setObjectName(_fromUtf8("btnCancel_2"))
        self.horizontalLayout_4.addWidget(self.btnCancel_2)
        self.labIcoMain_3 = QtGui.QLabel(self.tab_2)
        self.labIcoMain_3.setGeometry(QtCore.QRect(10, 30, 45, 45))
        self.labIcoMain_3.setStyleSheet(_fromUtf8("border-image: url(:/image/myconfig.png);"))
        self.labIcoMain_3.setText(_fromUtf8(""))
        self.labIcoMain_3.setObjectName(_fromUtf8("labIcoMain_3"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(70, 20, 651, 451))
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_4 = QtGui.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(100, 40, 71, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_9)
        self.label_5.setGeometry(QtCore.QRect(70, 180, 111, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(60, 240, 181, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(70, 100, 101, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 180, 251, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 240, 251, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.labIcoMain_4 = QtGui.QLabel(self.tab_3)
        self.labIcoMain_4.setGeometry(QtCore.QRect(10, 30, 45, 45))
        self.labIcoMain_4.setStyleSheet(_fromUtf8("border-image: url(:/image/myconfig.png);"))
        self.labIcoMain_4.setText(_fromUtf8(""))
        self.labIcoMain_4.setObjectName(_fromUtf8("labIcoMain_4"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(110, 590, 621, 34))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btnOk_3 = QtGui.QPushButton(self.layoutWidget_3)
        self.btnOk_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOk_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOk_3.setStyleSheet(_fromUtf8(""))
        self.btnOk_3.setIcon(icon)
        self.btnOk_3.setIconSize(QtCore.QSize(20, 20))
        self.btnOk_3.setObjectName(_fromUtf8("btnOk_3"))
        self.horizontalLayout_6.addWidget(self.btnOk_3)
        self.btnCancel_3 = QtGui.QPushButton(self.layoutWidget_3)
        self.btnCancel_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel_3.setStyleSheet(_fromUtf8(""))
        self.btnCancel_3.setIcon(icon1)
        self.btnCancel_3.setIconSize(QtCore.QSize(20, 20))
        self.btnCancel_3.setObjectName(_fromUtf8("btnCancel_3"))
        self.horizontalLayout_6.addWidget(self.btnCancel_3)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.widget_main)

        self.retranslateUi(configBox)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox_3.setCurrentIndex(0)
        self.toolBox_4.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(configBox)

    def retranslateUi(self, configBox):
        configBox.setWindowTitle(_translate("configBox", "提示", None))
        self.btnMenu_Close.setToolTip(_translate("configBox", "关闭", None))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_6), _translate("configBox", "tx-ht20", None))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_7), _translate("configBox", "tx-ht40", None))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_8), _translate("configBox", "rx", None))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "线损", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_9), _translate("configBox", "频率—线损", None))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "功率", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_10), _translate("configBox", "速率—功率", None))
        self.groupBox_6.setTitle(_translate("configBox", "其他", None))
        self.label_13.setText(_translate("configBox", "ppm limit ", None))
        self.label_14.setText(_translate("configBox", "ht40 power limit ", None))
        self.label_15.setText(_translate("configBox", "pcdac", None))
        self.label_27.setText(_translate("configBox", "ht20 power limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("configBox", "2.4G", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("configBox", "tx-ht20", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("configBox", "tx-ht40", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "速率", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("configBox", "天线", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("configBox", "rx", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "线损", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("configBox", "频率—线损", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("configBox", "频率", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("configBox", "功率", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("configBox", "速率—功率", None))
        self.groupBox_5.setTitle(_translate("configBox", "其他", None))
        self.label_8.setText(_translate("configBox", "ppm limit ", None))
        self.label_2.setText(_translate("configBox", "ht40 power limit ", None))
        self.label_9.setText(_translate("configBox", "pcdac", None))
        self.label_10.setText(_translate("configBox", "ht20 power limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("configBox", "5G", None))
        self.btnOk.setText(_translate("configBox", "确定(&O)", None))
        self.btnCancel.setText(_translate("configBox", "取消(&C)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("configBox", "测试项目配置", None))
        self.label_23.setText(_translate("configBox", "默认连接地址：", None))
        self.label_25.setText(_translate("configBox", "用户名：", None))
        self.label_26.setText(_translate("configBox", "密码：", None))
        self.label.setText(_translate("configBox", "2G端口：", None))
        self.label_3.setText(_translate("configBox", "5G端口：", None))
        self.groupBox_7.setTitle(_translate("configBox", "测试项目：", None))
        self.radioButton_6.setText(_translate("configBox", "MAC", None))
        self.radioButton_7.setText(_translate("configBox", "SN", None))
        self.groupBox_8.setTitle(_translate("configBox", "是否校准：", None))
        self.radioButton_8.setText(_translate("configBox", "是", None))
        self.radioButton_9.setText(_translate("configBox", "否", None))
        self.groupBox_3.setTitle(_translate("configBox", "测试类别", None))
        self.radioButton.setText(_translate("configBox", "仅测试2.4G", None))
        self.radioButton_2.setText(_translate("configBox", "仅测试5G", None))
        self.radioButton_3.setText(_translate("configBox", "测试2.4G和5G", None))
        self.btnOk_2.setText(_translate("configBox", "确定(&O)", None))
        self.btnCancel_2.setText(_translate("configBox", "取消(&C)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("configBox", "测试工作配置", None))
        self.label_4.setText(_translate("configBox", "老化时间：", None))
        self.label_5.setText(_translate("configBox", "日志保存路径：", None))
        self.label_6.setText(_translate("configBox", "测B站线损文件：", None))
        self.label_7.setText(_translate("configBox", "最大使用次数：", None))
        self.btnOk_3.setText(_translate("configBox", "确定(&O)", None))
        self.btnCancel_3.setText(_translate("configBox", "取消(&C)", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("configBox", "测试环境配置", None))

